version: '3.8'

services:
  db:
    image: postgres
    container_name: PostgreSQL
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: Database-API
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      API_KEY: 'supersecretkey' # example
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: master
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8089"]

volumes:
  postgres_data:
